<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ynohW8-64b-one" name="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero" tests="1" failures="1" timestamp="26 Aug 2017 00:00:13 GMT" time="213.218" errors="0">
  <testcase name="VoiceOACD_ByAbandon_CConference_ToExt_DifferentGroup" time="213.218" classname="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero">
    <failure type="java.lang.AssertionError" message="VoiceOACD_ByAbandon-&gt;Ans-&gt;Consult Conference to Ext on Different Group has failed because =&gt; 
@ agent1yc1@c1yc1.comfail on =&gt; btnConference expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceOACD_ByAbandon->Ans->Consult Conference to Ext on Different Group has failed because => 
@ agent1yc1@c1yc1.comfail on => btnConference expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero.VoiceOACD_ByAbandon_CConference_ToExt_DifferentGroup(Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceOACD_ByAbandon_CConference_ToExt_DifferentGroup -->
</testsuite> <!-- HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero -->
